services:

    # PostgreSQL version 16.1
    postgres:
        image: postgres:16.1
        container_name: postgres
        platform: linux/arm64/v8
        restart: always
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        volumes:
          - postgres:/var/lib/postgresql/data

volumes:
    postgres:
